services:
  postgres:
    image: postgres:17
    container_name: jobtracker-postgres
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: jobtracker-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobtracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: my-super-secret-key-that-is-at-least-32-characters-long
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"

volumes:
  postgres-data: